name: Docker build

on:
  release:
    types:
      - released

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Clone private assets repo into checked out directory
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.PRIVATE_ASSETS_PRIVATE_KEY }}"
          git clone git@github.com:BenShoeman/SonicOCBot-private-assets.git $GITHUB_WORKSPACE/../PrivateAssets
          rsync -a $GITHUB_WORKSPACE/../PrivateAssets/ $GITHUB_WORKSPACE/

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to image registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sonicocbot/sonicocbot:latest,sonicocbot/sonicocbot:${{ github.ref_name }}
