name: Make post

on:
  schedule:
  - cron: "30 * * * *"

  workflow_dispatch:

env:
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

jobs:
  make-post:
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone to US Central
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Chicago"

      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up Miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: sonicocbot
          python-version: 3.9
          channels: conda-forge
          allow-softlinks: true
          channel-priority: strict
          use-only-tar-bz2: true

      - name: Install dependencies
        run: |
          conda install --file $GITHUB_WORKSPACE/requirements/ghactions/conda.txt

      - name: Clone private assets repo and copy into checked out directory
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.PRIVATE_ASSETS_PRIVATE_KEY }}"
          git clone git@github.com:BenShoeman/SonicOCBot-private-assets.git $GITHUB_WORKSPACE/../PrivateAssets
          rsync -a $GITHUB_WORKSPACE/../PrivateAssets/ $GITHUB_WORKSPACE/

      - name: Run main script
        run: python $GITHUB_WORKSPACE/main.py
