name: Make post

on:
  schedule:
  - cron: "0 */3 * * *"
  - cron: "30 1/3 * * *"
  # Run every 90 minutes

  workflow_dispatch:

env:
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  TUMBLR_CONSUMER_KEY: ${{ secrets.TUMBLR_CONSUMER_KEY }}
  TUMBLR_CONSUMER_SECRET: ${{ secrets.TUMBLR_CONSUMER_SECRET }}
  TUMBLR_OAUTH_TOKEN: ${{ secrets.TUMBLR_OAUTH_TOKEN }}
  TUMBLR_OAUTH_SECRET: ${{ secrets.TUMBLR_OAUTH_SECRET }}

jobs:
  make-post:
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone to US Central
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Chicago"

      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Clone private assets repo into checked out directory
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.PRIVATE_ASSETS_PRIVATE_KEY }}"
          git clone git@github.com:BenShoeman/SonicOCBot-private-assets.git $GITHUB_WORKSPACE/../PrivateAssets
          rsync -a $GITHUB_WORKSPACE/../PrivateAssets/ $GITHUB_WORKSPACE/

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Set up pip cache
        uses: actions/cache@v2
        id: venv-cache
        with:
          path: .venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements/gha.txt') }}

      - name: Set up venv
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r $GITHUB_WORKSPACE/requirements/gha.txt

      - name: Set up Chrome browser
        uses: browser-actions/setup-chrome@latest

      - name: Make post
        run: |
          source .venv/bin/activate
          CHROME_BIN=$(which chrome) python $GITHUB_WORKSPACE/main.py
