name: Make post

on:
  schedule:
  - cron: "0 1/3 * * *"
  - cron: "30 2/3 * * *"

  workflow_dispatch:

env:
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      
      - name: Add Conda to PATH
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda env update --file $GITHUB_WORKSPACE/requirements-conda-min.txt --name base
          pip install -r $GITHUB_WORKSPACE/requirements-pip-min.txt

      - name: Clone private assets repo and copy into checked out directory
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.PRIVATE_ASSETS_PRIVATE_KEY }}"
          git clone git@github.com:BenShoeman/SonicOCBot-private-assets.git $GITHUB_WORKSPACE/../PrivateAssets
          rsync -a $GITHUB_WORKSPACE/../PrivateAssets/ $GITHUB_WORKSPACE/
      
      - name: Run main script
        run: python $GITHUB_WORKSPACE/main.py
