name: Make post

on:
  schedule:
  - cron: "30 * * * *"

  workflow_dispatch:

jobs:
  make-post:
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone to US Central
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "America/Chicago"

      - name: Run Docker image
        uses: addnab/docker-run-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          image: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/sonicocbot:latest
          options: |
            -e TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }}
            -e TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }}
            -e TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}
            -e TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
            -e TUMBLR_CONSUMER_KEY=${{ secrets.TUMBLR_CONSUMER_KEY }}
            -e TUMBLR_CONSUMER_SECRET=${{ secrets.TUMBLR_CONSUMER_SECRET }}
            -e TUMBLR_OAUTH_TOKEN=${{ secrets.TUMBLR_OAUTH_TOKEN }}
            -e TUMBLR_OAUTH_SECRET=${{ secrets.TUMBLR_OAUTH_SECRET }}
            -e MASTODON_INSTANCE_URL=${{ secrets.MASTODON_INSTANCE_URL }}
            -e MASTODON_ACCESS_TOKEN=${{ secrets.MASTODON_ACCESS_TOKEN }}
          run: python3 main.py
