name: Generate documentation

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone to US Central
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Chicago"

      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Clone private assets repo into checked out directory
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.PRIVATE_ASSETS_PRIVATE_KEY }}"
          git clone git@github.com:BenShoeman/SonicOCBot-private-assets.git $GITHUB_WORKSPACE/../PrivateAssets
          rsync -a $GITHUB_WORKSPACE/../PrivateAssets/ $GITHUB_WORKSPACE/

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Set up pip cache
        uses: actions/cache@v2
        id: venv-cache
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements/gha.txt') }}

      - name: Set up venv
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: python -m venv ./.venv && source ./.venv/bin/activate && pip install -r $GITHUB_WORKSPACE/requirements/gha.txt

      - name: Generate docs
        run: source ./.venv/bin/activate && pdoc --docformat numpy -o docs/ src

      - run: tar --directory docs/ -hcf artifact.tar .
      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./artifact.tar

  deploy-docs:
    needs: generate-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
