name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install mypy black

      - name: Run quality checks
        run: bash $GITHUB_WORKSPACE/quality-check.sh
