name: Quality checks

on:
  pull_request:
    branches: 
      - master

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Set up pip cache
        uses: actions/cache@v2
        id: venv-cache
        with:
          path: .venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements/gha.txt') }}

      - name: Set up venv
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r $GITHUB_WORKSPACE/requirements/gha.txt

      - name: Run quality checks
        run: |
          source .venv/bin/activate
          bash $GITHUB_WORKSPACE/quality-check.sh
